name: akyron_rpg
description: "Akyron RPG — RPG mobile + PC inspirado nos maiores animes de batalha. Híbrido online/offline construído em Flutter + Flame."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  # Engine
  flame: ^1.18.0
  flame_audio: ^2.10.0
  flame_tiled: ^1.20.0
  flame_noise: ^0.1.0

  # Estado e DI
  flutter_riverpod: ^2.5.1
  equatable: ^2.0.5

  # Save local
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3        # desktop (Windows / Linux / macOS)
  path_provider: ^2.1.3
  path: ^1.9.0
  shared_preferences: ^2.2.3

  # Online
  supabase_flutter: ^2.5.0
  web_socket_channel: ^3.0.0
  http: ^1.2.1

  # Utilidades
  uuid: ^4.4.0
  collection: ^1.18.0
  meta: ^1.12.0
  intl: ^0.19.0

  # UI extras
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/characters/
    - assets/images/clothing/
    - assets/images/effects/
    - assets/images/tiles/
    - assets/images/ui/
    - assets/audio/
    - assets/audio/music/
    - assets/audio/sfx/
    - assets/audio/ambient/
    - assets/data/

  fonts:
    - family: AkyronTitle
      fonts:
        - asset: assets/fonts/AkyronTitle-Regular.ttf
        - asset: assets/fonts/AkyronTitle-Bold.ttf
          weight: 700
    - family: AkyronBody
      fonts:
        - asset: assets/fonts/AkyronBody-Regular.ttf
